export const SAVETICKETALL ='saveticketall'
export const SAVETICKET ='saveticket'
export const SAVEUSERINFO ='saveuserinfo'
export const SAVEALBUM ='savealbum'
export const SAVEFORYOULIST ='saveforyoulist'
export const SAVEDISHINFO ='savedishinfo'
